name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile
        run: ./gradlew classes
      - name: Verify
        run: ./gradlew check -x test
      - name: JUnit Test
        run: ./gradlew test
      - name: Publish
        run: ./gradlew publishToMavenLocal