name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set Version
        id: set-version
        run: "./gradlew properties -q | grep version: | awk '{print \"::set-output name=version::\" $2}'"
      - name: Print Version
        run: echo "Version ${{ steps.set-version.outputs.version }}"
      - name: Compile
        run: ./gradlew assemble
      - name: Perform Release
        if: ${{ !contains(steps.set-version.outputs.version, 'SNAPSHOT') }}
        run: echo "Releasing version ${{ steps.set-version.outputs.version }}"
      - name: Perform Release
        if: ${{ !contains(steps.set-version.outputs.version, 'SNAPSHOT') }}
        run: |
          git config --global user.email "${{ github.actor }}"
          git config --global user.name "${{ github.actor }}"
          git tag -a v${{ steps.set-version.outputs.version }} -m "Version ${{ steps.set-version.outputs.version }}"
          ./gradlew incrementPatch -Dversion.prerelease=SNAPSHOT
          git add version.properties
          git commit -m "Incrementing to next SNAPSHOT patch version"
          git push --follow-tags